### ISSUE TITLE
Speed options

### ISSUE THREAD

**Issue by vincentj10** [LAEQ/vifeco#28]
Hi David,
Would it be possible to add an option to reduce video speed down to 0.10 please?
Currently it only goes down to 0.25.
All the best
Vincent

**Comment by davidmaignan** [comment]
OK. Very easy to change. You should be notified automatically once I publish a newer version. I'll give you few more days if you create more issues. I'm thinking to release a version once a month. It's quite time-consuming to create an installer for each OS.

**Comment by vincentj10** [comment]
Alright thanks
