### ISSUE TITLE
Space shortcut for play/pause

### ISSUE THREAD

**Issue by vincentj10** [LAEQ/vifeco#29]
Hi David,
In previous versions, it was possible to hit the space bar to pause/play the video. Would it be possible to bring back this feature in the new versions (3+) please? 
All the best,
Vincent

**Comment by davidmaignan** [comment]
The space bar is already used by JavaFX to keep/interact with the focus (previously pressed UI widget). You can play/pause the video with the Ctrl btn instead.

**Comment by vincentj10** [comment]
Thank you, both functions work well.
