### ISSUE TITLE
Add a fixed line/bar to have a reference 

### ISSUE THREAD

**Issue by bogaracha** [LAEQ/vifeco#40]
Is it possible to add a kind of static line or bar over the video screen to have a reference in the count mode?

Thanks in advance 👍

**Comment by davidmaignan** [comment]
I'm not sure to understand what this request is. Can you provide a mock up (drawing) to help visualize the static line/bar. 
- What does it represent ?
- size, color, positionning, ...

**Comment by bogaracha** [comment]
I show you an example made in Paint:
<img width="456" alt="RAW with line" src="https://user-images.githubusercontent.com/57992399/175777362-4fac4579-5be5-4a04-88c0-345d39ab8eb0.PNG">

The bar represents a tool that helps me to delimit an area for count the fishes in my video. 
The size, color or positionning it is variable. For example, in my case I would appreciate it if it were a yellow bar (contrasts with the blue water), vertical, adjustable in size and relatively thin.

Thanks 👍

**Comment by davidmaignan** [comment]
Is it only a visual help or does it require some kind of logic for exemple if u click outside the limit min/max the click is ignored?

**Comment by bogaracha** [comment]
It is only a visual help. Indeed, sometimes we use another software to paint in the screen to make a line.

**Comment by davidmaignan** [comment]
Implemented in 3.0.5
