### ISSUE TITLE
Add new features in controls, like brightness, saturation and contrast

### ISSUE THREAD

**Issue by bogaracha** [LAEQ/vifeco#41]
Is it possible add new features in the count mode that affects the video, like brightness, saturation and contrast?

Thanks in advance 👍

**Comment by davidmaignan** [comment]
Can you provide a mock up to illustrate your request.  As well as any use case to help me understand.

**Comment by bogaracha** [comment]
Yes, of course. I'm using Vifeco to count some tuna fishes in the water and sometimes there are choppy water, with organic material is suspension. Playing with the contrast, the brighness, the color saturation it can obtain a better view to count the fishes.
Find attached some examples
![RAW video](https://user-images.githubusercontent.com/57992399/175649059-7e75f97a-1908-4bd6-89d6-0e25c9bbb937.PNG)

![Modified video](https://user-images.githubusercontent.com/57992399/175649051-75c89f5e-f813-42a5-b4ad-4a4be03a4431.PNG)

What I want to know is if it is possible to add some bars, similar to those of the control panel (icon duration, speed...), to modify the features of color, brightness, contrast in the reproduced video.
