### ISSUE TITLE
Move back and forward with mouse scroll

### ISSUE THREAD

**Issue by 13nudos** [LAEQ/vifeco#44]
Hi,

Would it be possible to implement a function to be able to move back and forward with the mouse scroll in the video? So that you could go forward or backward **frame by frame**. This is very useful for fish counting, when all fish are close together and you need to go back/forward to accurately put a counting tag on each fish.

On the other hand, 
I would appreciate if you could tell me what code should I use if I want to create these icons: "+" and "-".
For example, I use this code to count fish: "_M35 10 L20 2 L20 20 Z_", which is a green triangle (color #008000), and the same icon in red for returning fish. But I would like to just use the "+" and "-" icons.

Thank you very much for your help.

**Comment by davidmaignan** [comment]
For the icons, I use this website https://iconmonstr.com/. You can download the svg version and select the path section.
